# Generated by Django 4.2.16 on 2024-11-25 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kor_co_nm', models.CharField(max_length=255, null=True)),
                ('fin_prdt_nm', models.CharField(max_length=255, null=True)),
                ('join_way', models.CharField(blank=True, max_length=255, null=True)),
                ('join_member', models.CharField(blank=True, max_length=255, null=True)),
                ('join_price', models.IntegerField(blank=True, null=True)),
                ('intr_rate_type', models.CharField(blank=True, max_length=255, null=True)),
                ('intr_rate_type_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('save_trm', models.IntegerField(blank=True, null=True)),
                ('intr_rate', models.FloatField(blank=True, null=True)),
                ('intr_rate2', models.FloatField(blank=True, null=True)),
                ('age_range', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'deposit_recommend',
            },
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kor_co_nm', models.CharField(max_length=255, null=True)),
                ('fin_prdt_nm', models.CharField(max_length=255, null=True)),
                ('join_way', models.CharField(blank=True, max_length=255, null=True)),
                ('join_member', models.CharField(blank=True, max_length=255, null=True)),
                ('etc_note', models.TextField(blank=True, null=True)),
                ('intr_rate_type', models.CharField(blank=True, max_length=255, null=True)),
                ('intr_rate_type_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('rsrv_type', models.CharField(blank=True, max_length=255, null=True)),
                ('rsrv_type_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('save_trm', models.IntegerField(blank=True, null=True)),
                ('intr_rate', models.FloatField(blank=True, null=True)),
                ('intr_rate2', models.FloatField(blank=True, null=True)),
                ('age_range', models.CharField(blank=True, max_length=50, null=True)),
                ('join_price', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'savings_recommend',
            },
        ),
        migrations.CreateModel(
            name='SavingsLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('savings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='products.savings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavingsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('savings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.savings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepositLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='products.deposit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepositComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.deposit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
