# Generated by Django 4.2.16 on 2024-11-21 14:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recommend", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comment",
            new_name="DepositComment",
        ),
        migrations.RenameModel(
            old_name="Like",
            new_name="DepositLike",
        ),
    ]
