# Generated by Django 4.2.16 on 2024-11-22 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_savingslike_savingscomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savingscomment',
            old_name='deposit',
            new_name='savings',
        ),
        migrations.RenameField(
            model_name='savingslike',
            old_name='deposit',
            new_name='savings',
        ),
    ]
