# Generated by Django 4.2.16 on 2024-11-22 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_rename_deposit_savingscomment_savings_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kor_co_nm", models.CharField(max_length=255, null=True)),
                ("fin_prdt_nm", models.CharField(max_length=255, null=True)),
                ("join_way", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "join_member",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("join_price", models.IntegerField(blank=True, null=True)),
                (
                    "intr_rate_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "intr_rate_type_nm",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("save_trm", models.IntegerField(blank=True, null=True)),
                ("intr_rate", models.FloatField(blank=True, null=True)),
                ("intr_rate2", models.FloatField(blank=True, null=True)),
                ("age_range", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "deposit_recommend",
            },
        ),
        migrations.CreateModel(
            name="Savings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kor_co_nm", models.CharField(max_length=255, null=True)),
                ("fin_prdt_nm", models.CharField(max_length=255, null=True)),
                ("join_way", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "join_member",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("etc_note", models.TextField(blank=True, null=True)),
                (
                    "intr_rate_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "intr_rate_type_nm",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("rsrv_type", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "rsrv_type_nm",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("save_trm", models.IntegerField(blank=True, null=True)),
                ("intr_rate", models.FloatField(blank=True, null=True)),
                ("intr_rate2", models.FloatField(blank=True, null=True)),
                ("age_range", models.CharField(blank=True, max_length=50, null=True)),
                ("join_price", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "savings_recommend",
            },
        ),
        migrations.AlterField(
            model_name="depositcomment",
            name="deposit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="products.deposit",
            ),
        ),
        migrations.AlterField(
            model_name="depositlike",
            name="deposit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="products.deposit",
            ),
        ),
        migrations.AlterField(
            model_name="savingscomment",
            name="savings",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="products.savings",
            ),
        ),
        migrations.AlterField(
            model_name="savingslike",
            name="savings",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="products.savings",
            ),
        ),
    ]
