# Generated by Django 4.2.16 on 2024-11-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('interest_rate', models.FloatField()),
                ('saving_period', models.CharField(max_length=50)),
                ('joining_method', models.CharField(max_length=50)),
                ('interest_type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'deposit_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('interest_rate', models.FloatField()),
                ('saving_period', models.CharField(max_length=50)),
                ('joining_method', models.CharField(max_length=50)),
                ('interest_type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'savings_table',
                'managed': False,
            },
        ),
    ]
