# Generated by Django 4.2.16 on 2024-11-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kor_co_nm', models.CharField(max_length=255, null=True)),
                ('fin_prdt_nm', models.CharField(max_length=255, null=True)),
                ('join_way', models.CharField(blank=True, max_length=255, null=True)),
                ('join_member', models.CharField(blank=True, max_length=255, null=True)),
                ('join_price', models.IntegerField(blank=True, null=True)),
                ('intr_rate_type', models.CharField(blank=True, max_length=255, null=True)),
                ('intr_rate_type_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('save_trm', models.IntegerField(blank=True, null=True)),
                ('intr_rate', models.FloatField(blank=True, null=True)),
                ('intr_rate2', models.FloatField(blank=True, null=True)),
                ('age_range', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'deposit_product',
            },
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kor_co_nm', models.CharField(max_length=255, null=True)),
                ('fin_prdt_nm', models.CharField(max_length=255, null=True)),
                ('join_way', models.CharField(blank=True, max_length=255, null=True)),
                ('join_member', models.CharField(blank=True, max_length=255, null=True)),
                ('etc_note', models.TextField(blank=True, null=True)),
                ('intr_rate_type', models.CharField(blank=True, max_length=255, null=True)),
                ('intr_rate_type_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('rsrv_type', models.CharField(blank=True, max_length=255, null=True)),
                ('rsrv_type_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('save_trm', models.IntegerField(blank=True, null=True)),
                ('intr_rate', models.FloatField(blank=True, null=True)),
                ('intr_rate2', models.FloatField(blank=True, null=True)),
                ('age_range', models.CharField(blank=True, max_length=50, null=True)),
                ('join_price', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'savings_product',
            },
        ),
    ]
