# Generated by Django 4.2.16 on 2024-11-22 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_deposit_savings_alter_depositcomment_deposit_and_more"),
        ("recommend", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Deposit",
        ),
        migrations.DeleteModel(
            name="Savings",
        ),
    ]
